# Generated by Django 4.2.23 on 2025-06-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Justificado')], default='presente', max_length=50)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info_Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familia', models.CharField(max_length=100)),
                ('numero_integrantes', models.IntegerField()),
                ('cuantos_trabajan', models.IntegerField()),
                ('ocupacion_padres', models.CharField(max_length=100)),
                ('estado_marital_padres', models.CharField(choices=[('casados', 'Casados'), ('separados', 'Separados'), ('anulado', 'Anulado'), ('convivientes', 'Convivientes'), ('viudo', 'Viudo'), ('viuda', 'Viuda'), ('solteros', 'Solteros'), ('divorciado', 'Divorciado')], default='casados', max_length=50)),
                ('estado_vida_padres', models.CharField(choices=[('ambos_vivos', 'Ambos Vivos'), ('ambos_fallecidos', 'Ambos Fallecidos'), ('padre_fallecido', 'Padre Fallecido'), ('madre_fallecida', 'Madre Fallecida')], default='ambos_vivos', max_length=50)),
                ('ingresos_mensuales', models.BigIntegerField()),
                ('cantidad_dormitorios', models.IntegerField()),
                ('cantidad_banos', models.IntegerField()),
                ('banos_compartidos', models.BooleanField(default=False)),
                ('energia', models.CharField(choices=[('red_electrica', 'Red Eléctrica')], default='red_electrica', max_length=50)),
                ('tipo_agua', models.CharField(choices=[('alcantarillado', 'Alcantarillado'), ('pozo', 'Pozo'), ('sin_acceso', 'Sin Acceso'), ('con_bomba', 'Con Bomba'), ('llave_en_vivienda', 'Llave en Vivienda'), ('llave_en_sitio', 'Llave en Sitio')], default='alcantarillado', max_length=50)),
                ('tipo_construccion', models.CharField(choices=[('casa_solida', 'Casa Sólida'), ('casa_madera', 'Casa de Madera'), ('departamento', 'Departamento'), ('arriendo', 'Arriendo'), ('media_agua', 'Media Agua')], default='casa_solida', max_length=50)),
                ('propiedad', models.CharField(choices=[('propia', 'Propia'), ('cedida', 'Cedida'), ('arrendada', 'Arrendada'), ('allegados', 'Allegados')], default='propia', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('RUN', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.genero')),
                ('id_nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_religion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('RUN_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.persona')),
                ('profesion', models.CharField(max_length=100)),
                ('lugar_de_trabajo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('RUN_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('RUN_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.persona')),
                ('anio_ingreso', models.IntegerField()),
                ('numero_de_matricula', models.CharField(max_length=50, unique=True)),
                ('fecha_matricula', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/')),
                ('estado_academico', models.CharField(choices=[('vigente', 'Vigente'), ('egresado', 'Egresado'), ('reiterado', 'Reiterado'), ('eliminado', 'Eliminado'), ('prematriculado', 'Prematriculado'), ('congelado', 'Congelado')], default='vigente', max_length=50)),
                ('semestre_ingreso', models.IntegerField()),
                ('id_familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.info_familia')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('RUN_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.persona')),
                ('titulo_academico', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar_de_Residencia',
            fields=[
                ('RUN_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.persona')),
                ('region', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero_casa', models.IntegerField()),
                ('numero_departamento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nombre_Completo',
            fields=[
                ('RUN_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.persona')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='id_religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.religion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.user'),
        ),
        migrations.CreateModel(
            name='Numero_Telefonico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_del_pais', models.IntegerField()),
                ('codigo_del_area', models.IntegerField()),
                ('numero_unico', models.IntegerField(unique=True)),
                ('RUN_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_justificacion', models.TextField()),
                ('id_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.asistencia')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('ponderacion', models.FloatField()),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.asignatura')),
                ('run_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('grado', models.IntegerField()),
                ('letra', models.CharField(default='A', max_length=1)),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.sala')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Bloque_Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='lunes', max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'unique_together': {('dia', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_bloque_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.bloque_horario'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.curso'),
        ),
        migrations.CreateModel(
            name='Actividad_Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=100)),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion_de_Trabajo',
            fields=[
                ('RUN_Apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.apoderado')),
                ('region', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero_casa', models.IntegerField()),
                ('numero_departamento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Numero_Telefonico_Trabajo',
            fields=[
                ('RUN_Apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.apoderado')),
                ('codigo_del_pais', models.IntegerField()),
                ('codigo_del_area', models.IntegerField()),
                ('numero_unico', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_accidente', models.TextField()),
                ('fecha', models.DateField()),
                ('RUN_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='RUN_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estudiante'),
        ),
        migrations.CreateModel(
            name='asignaturaESTAENbloquehorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.asignatura')),
                ('id_bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.bloque_horario')),
            ],
            options={
                'unique_together': {('id_asignatura', 'id_bloque_horario')},
            },
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_anotacion', models.TextField()),
                ('tipo_anotacion', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa')], max_length=50)),
                ('RUN_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='actividadESTAENELbloquehorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.actividad_extracurricular')),
                ('id_bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.bloque_horario')),
            ],
            options={
                'unique_together': {('id_actividad', 'id_bloque_horario')},
            },
        ),
        migrations.CreateModel(
            name='estudianteTOMAactividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.actividad_extracurricular')),
                ('RUN_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estudiante')),
            ],
            options={
                'unique_together': {('RUN_Estudiante', 'id_actividad')},
            },
        ),
        migrations.CreateModel(
            name='estudianteRINDEevaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.evaluacion')),
                ('RUN_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estudiante')),
            ],
            options={
                'unique_together': {('RUN_Estudiante', 'id_evaluacion')},
            },
        ),
        migrations.CreateModel(
            name='estudiantePERTENECEcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.curso')),
                ('RUN_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estudiante')),
            ],
            options={
                'unique_together': {('RUN_Estudiante', 'id_curso')},
            },
        ),
        migrations.CreateModel(
            name='docenteDICTAasignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.asignatura')),
                ('RUN_Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.docente')),
            ],
            options={
                'unique_together': {('RUN_Docente', 'id_asignatura')},
            },
        ),
        migrations.CreateModel(
            name='docenteACARGOactividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.actividad_extracurricular')),
                ('RUN_Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.docente')),
            ],
            options={
                'unique_together': {('RUN_Docente', 'id_actividad')},
            },
        ),
        migrations.CreateModel(
            name='apoderadoRESPONSABLEDEestudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(max_length=50)),
                ('RUN_Apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.apoderado')),
                ('RUN_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.estudiante')),
            ],
            options={
                'unique_together': {('RUN_Estudiante', 'RUN_Apoderado')},
            },
        ),
    ]
