# Generated by Django 4.2.23 on 2025-06-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='RUN',
            new_name='RUN_persona',
        ),
    ]
