# Generated by Django 4.2.23 on 2025-06-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_run_persona_run_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='RUN_persona',
            new_name='RUN',
        ),
    ]
